services:
# ==== Serviço da API ====
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag-faq-plurelo
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - UV_LINK_MODE=copy