name: Deploy to VM

on:
  push:
    branches:
      - main # Ou a branch que você usa para deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }} # IP da sua VM: 35.198.44.225
          username: ${{ secrets.SSH_USER }} # Seu usuário na VM: erickgaves
          key: ${{ secrets.SSH_PRIVATE_KEY }} # A chave que você adicionou nos secrets
          script: |
            # 1. Navega para o diretório do projeto, clonando se necessário
            if [ ! -d "rag-faq-plurelo" ]; then
              git clone https://github.com/SEU_USUARIO/rag-faq-plurelo.git
            fi
            cd rag-faq-plurelo

            # 2. Força a sincronização com o repositório remoto
            git fetch origin
            git reset --hard origin/main
            
            # 3. Remove o ficheiro .env antigo para garantir uma limpeza total
            rm -f .env

            # 4. Cria o novo arquivo .env com o valor do Secret do GitHub
            echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env

            # 5. Para e remove os containers antigos
            docker-compose down

            # 6. Reconstrói a imagem sem cache
            docker-compose build --no-cache

            # 7. Inicia os novos containers
            docker-compose up -d